version: '3'
services:
  postgres:
    image: postgres:12
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - TZ=Etc/UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seated

  redis:
    image: redis
    ports:
      - '6379:6379'
